# Generated by Django 5.2.6 on 2025-09-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profileuser_username'),
    ]

    operations = [
    ]
